export const Products = [
    {
      "id": 1,
      "sku": "F-001",
      "name": "Modern Sofa",
      "price": 1299.99,
      "short_description": "Sleek and comfortable sofa with clean lines.",
      "materials": "Velvet, Foam, Wood",
      "color": "Grey",
      "images": ["https://example.com/images/product1.jpg", "https://example.com/images/product1_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": true
    },
    {
      "id": 2,
      "sku": "F-002",
      "name": "Rustic Dining Table",
      "price": 899.99,
      "short_description": "Sturdy dining table with a natural wood finish.",
      "materials": "Oak Wood",
      "color": "Brown",
      "images": ["https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg", 
        "https://example.com/images/product2_2.jpg",
        "https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": true,
      "brand": "IKEA",
      "is_in_stock": true,
      "rating": 4.5,
      "model": "/models/Rustic_Dining_Table/scene.glb"
    },
    {
      "id": 3,
      "sku": "F-003",
      "name": "Minimalist_Bed",
      "price": 499.99,
      "short_description": "Simple and elegant bed frame for a modern bedroom.",
      "materials": "Metal",
      "color": "Black",
      "images": ["https://example.com/images/product3.jpg", "https://example.com/images/product3_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": true
    },
    {
      "id": 4,
      "sku": "F-004",
      "name": "Leather_Armchair",
      "price": 699.99,
      "short_description": "Luxurious armchair with premium leather upholstery.",
      "materials": "Leather, Foam",
      "color": "Tan",
      "images": ["https://example.com/images/product4.jpg", "https://example.com/images/product4_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    },
    {
      "id": 5,
      "sku": "F-005",
      "name": "Industrial_Bookshelf",
      "price": 299.99,
      "short_description": "Open-shelf bookshelf with a vintage industrial style.",
      "materials": "Metal, Wood",
      "color": "Black",
      "images": ["https://example.com/images/product5.jpg", "https://example.com/images/product5_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    },
    {
      "id": 6,
      "sku": "F-006",
      "name": "Mid-Century_Modern_Desk",
      "price": 399.99,
      "short_description": "Stylish desk with tapered legs and a minimalist design.",
      "materials": "Walnut Wood",
      "color": "Natural",
      "images": ["https://example.com/images/product6.jpg", "https://example.com/images/product6_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    },
    {
      "id": 7,
      "sku": "F-007",
      "name": "Velvet_Ottoman",
      "price": 149.99,
      "short_description": "Versatile ottoman with soft velvet upholstery.",
      "materials": "Velvet, Foam",
      "color": "Green",
      "images": ["https://example.com/images/product7.jpg", "https://example.com/images/product7_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    },
    {
      "id": 8,
      "sku": "F-008",
      "name": "Scandinavian_Dining_Chair",
      "price": 199.99,
      "short_description": "Comfortable dining chair with a minimalist Scandinavian style.",
      "materials": "Beech Wood, Fabric",
      "color": "White",
      "images": ["https://example.com/images/product8.jpg", "https://example.com/images/product8_2.jpg"],
      "uom": "Pair",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    },
    {
      "id": 9,
      "sku": "F-009",
      "name": "Rattan_Hanging_Chair",
      "price": 349.99,
      "short_description": "Relaxing hanging chair made of natural rattan.",
      "materials": "Rattan",
      "color": "Natural",
      "images": ["https://example.com/images/product9.jpg", "https://example.com/images/product9_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    },
    {
      "id": 10,
      "sku": "F-010",
      "name": "Glass_Coffee_Table",
      "price": 299.99,
      "short_description": "Modern coffee table with a sleek glass top.",
      "materials": "Glass, Metal",
      "color": "Clear",
      "images": ["https://example.com/images/product10.jpg", "https://example.com/images/product10_2.jpg"],
      "uom": "Piece",
      "thumbnail":"https://images.pexels.com/photos/5780838/pexels-photo-5780838.jpeg",
      "isFeatured": false
    }
  ]